apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: whoiscan/api-service:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: auth-service-url
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: order-service-url
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: product-service-url
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
    spring-boot: "true"
spec:
  ports:
    - port: 8090
      targetPort: 8080
      protocol: TCP
  selector:
    app: api-service
  type: LoadBalancer