apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: whoiscan/payment-service:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: database-password
            - name: TRANSACTION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: transaction-service-url
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-service
                  key: api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
    spring-boot: "true"
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: payment-service
  type: LoadBalancer