apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  database-password: YWRtaW4=
  database-user: YWRtaW4=
  database-auth-name: YWNjb3VudHMscGF5bWVudHMsb3JkZXJzLHByb2R1Y3Rz