apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  labels:
    app: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: whoiscan/transaction-service:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: BANKING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: banking-service-url
            - name: PAYPAL_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: paypal-service-url
            - name: CREDITCARD_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: services-configmap
                  key: creditcard-service-url
            - name: API_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-service
                  key: api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  labels:
    app: transaction-service
    spring-boot: "true"
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: transaction-service
  type: ClusterIP